### ISSUE TITLE
Use new sprites in Lesson 1

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/comp4kids#17]
We're using a stormtrooper in the place of a robot, and not using actual asteroids. The sprites should be changed, which also requires updating the functions that create them in util/animator/element_factories.js.

**Comment by nildo** [comment]
Now I added a sprite sheet for the asteroids in the branch new-robot-sprite. I still have an issue there. For each asteroid, I created an animation called random which assigns a random frame on the sprite sheet to it. But at the beginning, it always start with the first image, and only play the random animation when we press play. This animation should be played in the beginning so the asteroids are right.

**Comment by gpoesia** [comment]
Fixed by ed199cec59854ee5581772db89d85df5b20f89a8.
