### ISSUE TITLE
"Robot already holding a component" message does not show up in lesson 3

### ISSUE THREAD

**Issue by gpoesia** [gpoesia/comp4kids#48]
In lesson 3, if the robot is already holding a component and it executes another G command, execution halts with an empty error message. It should show a message related to what happened: the robot can only hold one component at a time.

This is probably just a typo in the message's constant name:

* The constant is defined here: https://github.com/gpoesia/comp4kids/blob/master/src/constants.js#L34
* And referenced here: https://github.com/gpoesia/comp4kids/blob/master/src/lesson/lesson03.js#L530

**Comment by msclar** [comment]
You're right, this is just a typo. I changed the reference to "TRIED_HOLDING_TWO_COMPONENTS" and the error message showed up fine (ignore the "play" button being displayed differently, I was working on a different issue):

![screenshot from 2016-09-30 02-02-54](https://cloud.githubusercontent.com/assets/8364317/18981179/2cb91958-86b2-11e6-8670-c5305dd83128.png)

I think that to be more coherent with the other error names on lesson03 it would make sense for "TRIED_HOLDING_TWO_COMPONENTS" to be called "CANNOT_HOLD_TWO_COMPONENTS". What do you think?

**Comment by gpoesia** [comment]
Perfect! Feel free to change the constant name too.
